---
title: Cat Classification #project name, goes to dashboard title
skin: blue #shinydashboard skin
user:
  - user: admin
    password: admin
    admin: true
  - user: test
    password: test
    admin: false
type: image #text or image
question:
  - text: Is there a cat? #what the user sees
    value: cat #name of question, will become the column name in the classification results
    choice:
      - name: "Yes" #what the user sees
        value: 1 #value to be recorded
      - name: "No"
        value: 0
  - text: If there is, what is its colour?
    value: color
    choice:
      - name: Not Applicable
        value: NA
      - name: Black
        value: black
      - name: Cinnamon
        value: cinnamon
      - name: Orange
        value: orange
      - name: Gray
        value: gray
      - name: Black
        value: black
...
