---
title: Cat Classification #project name, serve as dashboard title
skin: blue #shinydashboard skin
user:
  - user: admin
    password: admin
    admin: true
  - user: john
    password: john
    admin: false
type: image #text or image
question:
  - text: Is there a cat? #what the user sees
    value: cat #name of question, will become the column name in classification result
    type: radio #type of control element: radio (exclusive), checkbox (multiple), or selectize (exclusive/multiple)
    choice:
      - name: "Yes" #what the user sees
        value: 1 #value to be recorded
        keycode: 89 #shortcut key for quick selection, in JavaScript key code (optional)
      - name: "No"
        value: 0
        keycode: 78
  - text: If there is, what is its colour?
    type: selectize
    multiple: true #whether answers are exclusive or multiple, only applicable for selectize, default to exclusive if unspecified
    value: color
    choice:
      - name: Not Applicable
        value: NA
        keycode: 48
      - name: Black
        value: black
        keycode: 49
      - name: Cinnamon
        value: cinnamon
        keycode: 50
      - name: Orange
        value: orange
        keycode: 51
      - name: Gray
        value: gray
        keycode: 52
#shortcut keys for navigation (optional)
shortcut: 
  - action: submit #submit
    keycode: 13 #enter
  - action: prev #previous entry
    keycode: 37 #left arrow
  - action: next #next entry
    keycode: 39 #right arrow
...
